# -*- coding: utf-8 -*-
"""OASIS_Infobyte_Cleaning_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbptoSpPFSpqb6puSK_5CwJuSzRIBMYd

#**Cleaning Data**

Load the Dataset
"""

import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt

AB_NYC_2019 = pd.read_csv('/content/AB_NYC_2019.csv')

print(AB_NYC_2019.info())

print(AB_NYC_2019.describe)

print(AB_NYC_2019.dtypes)

print(AB_NYC_2019.head())

print(AB_NYC_2019.tail())

"""Handle Missing Data"""

print(AB_NYC_2019.isnull())

print(AB_NYC_2019.isnull().sum())

print(AB_NYC_2019.isnull().sum().sum())

"""Remove Duplicates"""

AB_NYC_2019 = AB_NYC_2019.drop_duplicates()

print(AB_NYC_2019.duplicated().sum())

"""Standardize Data

Identify non-numeric values in the latitude column
"""

non_numeric_latitude = AB_NYC_2019[~AB_NYC_2019['latitude'].astype(str).apply(lambda x: x.replace('.', '', 1).isdigit())]

print(non_numeric_latitude[['latitude', 'longitude']])

"""Remove rows with non-numeric latitude values"""

AB_NYC_2019_cleaned = AB_NYC_2019[AB_NYC_2019['latitude'].astype(str).apply(lambda x: x.replace('.', '', 1).isdigit())]

AB_NYC_2019_cleaned['latitude'] = AB_NYC_2019_cleaned['latitude'].astype(float)
AB_NYC_2019_cleaned['longitude'] = AB_NYC_2019_cleaned['longitude'].astype(float)

"""Handle Missing Data"""

AB_NYC_2019_cleaned['reviews_per_month'].fillna(0, inplace=True)
AB_NYC_2019_cleaned['last_review'].fillna('No Review', inplace=True)

"""Detect and Handle Outliers

Identify outliers in the 'price' column using IQR
"""

Q1 = AB_NYC_2019['price'].quantile(0.25)
Q3 = AB_NYC_2019['price'].quantile(0.75)
IQR = Q3 - Q1

"""Define outlier boundaries"""

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

"""Filter out outliers"""

AB_NYC_2019_cleaned = AB_NYC_2019[(AB_NYC_2019['price'] >= lower_bound) & (AB_NYC_2019['price'] <= upper_bound)]

"""Verify and Save the Cleaned Data"""

print(AB_NYC_2019_cleaned.info())

AB_NYC_2019_cleaned.to_csv('/content/AB_NYC_2019_cleaned.csv', index=False)